Facepunch/Facepunch.Steamworks

LICENSE

You mentioned the MIT license in the README.

Add LICENSE file (MIT)

---

LICENSE

Update the license file with the correct company and year.

Update license with company/year

---

Facepunch.Steamworks/Interfaces/Workshop.Item.cs
Facepunch.Steamworks/Interfaces/Workshop.cs
Facepunch.Steamworks/SteamNative/SteamNative.SteamUGC.cs

Added subscribing to items as well as the UGC interfaces
GetNumSubscribedItems and GetSubscribedItems. Edited SteamUGC Method
GetSubscribedItems to accept array instead of a ptr to allow c# calling

Implemented Workshop Item Subscription

---

.gitignore
Facepunch.Steamworks.Test/Client/Lobby.cs
Facepunch.Steamworks/Client.cs
Facepunch.Steamworks/Client/Lobby.cs
Facepunch.Steamworks/Client/LobbyList.Lobby.cs
Facepunch.Steamworks/Client/LobbyList.cs
README.md

Adds in Lobby functionality from the Steamworks API. All tests passing in Lobby.cs in the test project. Only thing currently missing is the ability to interop with Servers.

Adds in Lobby functionality to library

---

Facepunch.Steamworks.Test/Facepunch.Steamworks.Test.csproj
Facepunch.Steamworks/Client/Lobby.cs

Fixes issues with the Owner where it was being improperly (and unnecessarily) cached. Also fixes issue where you were unable to change the Lobby Owner.

Fixes issues with setting the Lobby Owner

---

Facepunch.Steamworks/Client.cs

This folder does not always exist.

Fixed InstallFolder exception

---

Facepunch.Steamworks.Test/Client/LobbyTest.cs
Facepunch.Steamworks/Client/LobbyList.Lobby.cs

To LobbyList.Lobby
Added Dictionary<string, string> GetAllData();
Added string GetData(string k);
Added string LobbyType { get; private set; }
With this you can list extra lobby parameters when displaying the Lobby List, such as current played map or game mode.

Added Lobby data getters for LobbyList.Lobby (plus extra LobbyType)

---

Facepunch.Steamworks/Client/Friends.cs

I have add a simple function for enable send invitations to friends start from line 143.

Update for can send invitations.

---

Facepunch.Steamworks/Client/Leaderboard.cs

Why was this missing in the first place? @garrynewman please verify and merge

Added FetchUsersScores to Leaderboard.cs

---

Facepunch.Steamworks/Client/Leaderboard.cs

Was needed it for Steam WebAPI

Added Leaderboard.GetBoardId() to access boardID

---

Facepunch.Steamworks.Test/Client/RichPresenceTest.cs
Facepunch.Steamworks/Client/User.cs

Added documentation for rich presence. Changed SetRichPresence return type to bool. Updated rich presence test.

Improvements for rich presence

---

Facepunch.Steamworks/Facepunch.Steamworks.csproj

This otherwise shows as 'Package description'.

Add NuGet package description

---

Facepunch.Steamworks/SteamNetworkingSockets.cs
Facepunch.Steamworks/SteamServer.cs

Install SteamNetworkingSockets events when initializing SteamServer

---

Facepunch.Steamworks/SteamMatchmaking.cs

Added an OnLobbyEntered action with associated LobbyEnter_t event install, and added a JoinLobbyAsync method which returns the joined lobby if successful
Second commit is because I pushed it with spaces instead of tabs initially

 Pull req - OnLobbyEntered Action and JoinLobbyAsync

---

Facepunch.Steamworks/Structs/UgcItem.cs
Facepunch.Steamworks/Structs/UgcQuery.cs

Added Steamworks.Ugc.Query.WhereSearchText
Added Steamworks.Ugc.Item.VotesUp
Added Steamworks.Ugc.Item.VotesDown
Added Steamworks.Ugc.Item.Subscribe
Added Steamworks.Ugc.Item.Unsubscribe

Added missing functionality to UgcQuery and UgcItem

---

Facepunch.Steamworks/SteamMatchmaking.cs
Facepunch.Steamworks/SteamNetworking.cs
Facepunch.Steamworks/SteamUserStats.cs
Facepunch.Steamworks/Structs/Lobby.cs
Facepunch.Steamworks/Structs/SteamId.cs

Added SetGameServer and GetGameServer for lobby, added OnLobbyGameCreated event in SteamMatchmaking, added SteamId.IsValid check against default ulong value, added SteamUserStats.IndicateAchievementProgress for progress notification.

Lobby game server methods, OnLobbyCreated and OnLobbyGameCreated, Achievement progress

---

Facepunch.Steamworks/SteamFriends.cs

Adds missing function from #305.

Add SteamFriends.GetFromSource

---

Facepunch.Steamworks/Generated/SteamEnums.cs
Facepunch.Steamworks/SteamFriends.cs
Generator/Cleanup.cs

Added SteamFriends.GetFriendsWithFlag as requested in #316 .
Reworked SteamFriends.GetFriends and SteamFriends.GetBlocked to work upon it.
I also had to expose the FriendFlags.

Added SteamFriends.GetFriendsWithFlag

---

Facepunch.Steamworks/Structs/UgcItem.cs

Let me know if there's any already implemented way to do it. 
I find `Action<float>` easier to implement than `IProgress<float>` used for ex. in `CreateItem`.

SubscribeDownloadAsync for workshop item

---

Facepunch.Steamworks/SteamServer.cs

shutdown server stats

---

Facepunch.Steamworks/SteamApps.cs

typo on AvailableLanguages

---

Facepunch.Steamworks/SteamFriends.cs

Expose IsFollowing, GetFollowerCount, and EnumerateFollowingList

---

Facepunch.Steamworks/Structs/Lobby.cs

Make Lobby ctor public

---

Facepunch.Steamworks/Structs/Connection.cs

Fixes #357 and possibly fixes #358

Make Id public only a getter

---

Facepunch.Steamworks/Structs/Leaderboard.cs

Last parameter for DownloadLeaderboardEntries is index inclusive

DownloadLeaderboardEntries count more precise

---

Facepunch.Steamworks/SteamClient.cs

Copied wording from https://wiki.facepunch.com/steamworks/Setting_Up#using

Document SteamClient.IsValid

---

Facepunch.Steamworks/Structs/UgcAdditionalPreview.cs
Facepunch.Steamworks/Structs/UgcAdditionalPreview.cs.meta
Facepunch.Steamworks/Structs/UgcItem.cs
Facepunch.Steamworks/Structs/UgcQuery.cs
Facepunch.Steamworks/Structs/UgcResultPage.cs

Also has #447 pull requests to avoid merge conflicts

Added ugc addtional previews

---

Facepunch.Steamworks/Generated/SteamEnums.cs
Facepunch.Steamworks/SteamFriends.cs

Adding ability for caller to specify OverlayToStoreFlags, to streamline purchasing DLC.

Allow caller to specify OverlayToStoreFlags when opening Store Overlay

---

Facepunch.Steamworks/SteamApps.cs

Just saw this in the wiki, didn't look right!

Fix 'IsLowVoilence' Typo

---

Facepunch.Steamworks/Generated/SteamEnums.cs
Facepunch.Steamworks/SteamUtils.cs
Generator/Cleanup.cs

Added support to use the Filter text functionality as mentioned on:
https://partner.steamgames.com/doc/api/ISteamUtils

Added support for FilterText
