Facepunch/Facepunch.Steamworks

- Facepunch.Steamworks/Client/Stats.cs
I ran into the exact issue described in #19 and dug a little into the Steamworks API.
It appears that Steamworks does not commit stat changes such as unlocked achievements to Steam until it is explicitly told to do so. (This happens implicitly during cleanup upon shutdown)
This pull request adds the missing Client.Stats.StoreStats() API-method that one needs to call to commit stat changes from Steamworks to Steam. Calling this method right after Client.Achievements.Trigger(...) will cause Steam overlay to show the appropriate achievement-unlocked toast immediately.
> Add missing Stats.StoreStats() API-method

- Facepunch.Steamworks/Interfaces/Workshop.cs
updated Workshop.onDownloadResult method to ensure that the item's app ID matches the client app id, as described in the DownloadItemResult_t Steamworks documentation.
`The ISteamUGC::DownloadItemResult_t callback struct contains the application ID (m_unAppID) associated with the workshop item. It should be compared against the running application ID as the handler will be called for all item downloads regardless of the running application.`
from [Steamworks Documentation](https://partner.steamgames.com/doc/features/workshop/implementation)
> Updated  Workshop.onDownloadResult to compare downloaded item's application to current application

- Facepunch.Steamworks/Interfaces/Workshop.cs
Similar to my last pull request, I realized that OnItemInstalled should be comparing the AppId of the downloaded file to that of the current application, so I added that comparison.
I also made the OnItemInstalled event public, so I could use it to determine when a workshop item has been subscribed to while playing the game, using the in-game overlay. It seems that the OnFileDownloaded event is not triggered when a workshop item is subscribed to, so I updated the summary accordingly.
> Made changes surrounding OnItemInstalled and OnFileDownloaded events in Workshop.cs

- Facepunch.Steamworks/Client/Screenshots.cs
Added AddScreenshotToLibrary(filename, thumbnailFilename, width, height); 
and AddScreenshotToLibrary(filename, width, height); 
We use Application.TakeScreenshot(path, superSize) in some of our in-game tools (like the camera) to allow for higher-res screenshots, 
and this feels like a much faster way of doing it then loading the PNG back into a texture2D, converting it into a correct format, and using Write to get it in Steam.
> Added AddScreenshotToLibrary

- Facepunch.Steamworks/Client/LobbyList.cs
Currently if a null filter is given, more filters are added to the call
than expected. This change makes a lobby request after the appid filter
is added and returns immediately resolving the issue.
> Correctly handle lobby refresh with null filter

- Facepunch.Steamworks/Config.cs
- Facepunch.Steamworks/SteamNative/SteamNative.Platform.cs
This occurs when a user is trying to run the .app outside of steam directly without steam running.
The .NET code incorrectly determines the system as Unix and thus goes down the method for binding against linux .so.
I've added a new run time platform function determination method that checks against the macOS 
```
case PlatformID.Unix:                    
// macOS sometimes reports to .NET as Unix. Fix is to check against macOS root folders
if (Directory.Exists("/Applications") && Directory.Exists("/System") && Directory.Exists("/Users") && Directory.Exists("/Volumes"))
return Facepunch.Steamworks.OperatingSystem.macOS;
else
return Facepunch.Steamworks.OperatingSystem.Linux;
```
This fixes the edge cases and prevents any strange macOS problems occurring 
- Also changed the enum to …
> Fix macOS Runtime Platform determination failing

- Facepunch.Steamworks/Config.cs
x86-x64 works fine, but x86 crash on startup.
Version 0.7 has lines:
//
// 32bit windows unity uses a stdcall
//
if ( IntPtr.Size == 4 ) UseThisCall = false;
This fixes the problem.
> Fixed Windows x86 build crash on startup

- Facepunch.Steamworks/Client.cs
- Facepunch.Steamworks/Interop/Native.cs
Exposed LoggedOn property to manually check the client if it's connected and logged on to the (online) Steam servers.
Pulling as to resolve  https://github.com/Facepunch/Facepunch.Steamworks/issues/174
I have used the change in a functioning project, and run provided tests (though some failed due to how differently my project is configured compared to the Rust). Please merge as to resolve future problems with offline mode.
> Resolved #174  - removed redundant check in InitClient to allow wrapper initialization in offline mode

- Facepunch.Steamworks/Client/Lobby.cs
GetData("joinable") returns "True" or "False", (note upercase), so the Joinable would always return false.
Fixed by setting to LowerInvariant, since I'm not sure if it returns it uppercase on other platforms as well, or if this ever gets changed.
> Fixed Lobby.Joinable

- Facepunch.Steamworks/SteamServer.cs
This callbacks allow to determine whether server connected and logged on to steam master server or not and when if so.
> Add ServersConnected and ServerConnectFailure callbacks to SteamServer

- Facepunch.Steamworks/SteamMatchmaking.cs
- Facepunch.Steamworks/Structs/LobbyQuery.cs
Added LobbyQuery FilterStringKeyValue methods, fixed spacing on SteamMatchmaking.LobbyEnter_t.Install() parameter
> LobbyQuery FilterStringKeyValue method

- Facepunch.Steamworks/SteamClient.cs
- Facepunch.Steamworks/Structs/Friend.cs
- Facepunch.Steamworks/Structs/Lobby.cs
- Facepunch.Steamworks/Structs/LobbyQuery.cs
- Facepunch.Steamworks/Structs/NumericalFilter.cs
Added LobbyQuery numerical filters for WithLower, WithHigher, WithEqual, and WithNotEqual; added OrderByNear for near value filters. Added OwnsLobby method to SteamClient and Friend which accepts a Lobby argument to test for ownership (replacing what I've been using: "if(SteamClient.SteamId == lobby.Owner.Id)")
> LobbyQuery Numerical and NearVal Filters, SteamClient and Friend OwnsLobby

- Facepunch.Steamworks/SteamNetworkingUtils.cs
`SteamNetworkingUtils.LocalTimestamp` was spelled _LocalTimetamp_ before.
> Fix typo SteamNetworkingUtils.LocalTimestamp

- Facepunch.Steamworks/SteamFriends.cs
GetFriends iterated by the Immediate Flag but didn't use the same flag to get the friend.
> Fixed GetFriends returning blocked friends

- Facepunch.Steamworks/SteamFriends.cs
Adds key/value to the dictionary only if the rich presence was set successfully. Also fixes #307
> Fix SteamFriends.GetRichPresence(key, value)

- Facepunch.Steamworks/SteamNetworking.cs
Adds unsafe overloads to SteamNetworking to avoid allocating garbage upon receiving messages. Some of these are thin wrappers around the actual internal call.
This is largely untested, but it's a trivial enough overload that it should work fine.
Also fixed the some indentation issues in the file.
> Add unsafe overloads for SteamNetworking P2P send and recieve functions

- Facepunch.Steamworks/Structs/UgcItem.cs
After `if ( !IsDownloading) ` state is set to DownloadPending and NeedsUpdate (for a split second) resulting in method returning false. Little random and doesn't happen while debugging but this fixes it.
> Fixed sometimes false returned from SubscribeDownloadAsync

- Facepunch.Steamworks/Structs/Leaderboard.cs
ISteamUserStats.cs provides an internal method called GetLeaderboardEntryCount that retrieves the total number of entries for a given leaderboard.
Following the convention already established in Leaderboard.cs for the property Name, a property called EntryCount has been added to Leaderboard.cs that publicly surfaces the GetLeaderboardEntryCount method.
I have built this fork of Facepunch.Steamworks locally and tested this property successfully works in a Unity project.
> Added EntryCount to Leaderboard

- Facepunch.Steamworks/Structs/InventoryDef.cs
Otherwise we get error in `_properties[name] = vl;` (line 109) as name is null. GetProperty(null) is called to get csv list of keys as string. I guess separate method would be cleaner but I'm keeping this example to minimum (or im too lazy).
> Fix for InvetoryDef Properties

- Facepunch.Steamworks/SteamServer.cs
I hunted for a good while for an existing method allowing a server to read its own SteamID (without parsing debug output), couldn't find anything.
So, I exposed the internal SteamId method as `SteamServer.SteamId`. I also added a dispatch listener for `SteamNetAuthenticationStatus_t` as `SteamServer.OnSteamNetAuthenticationStatus`
The reasoning for the listener is because it's a good opportunity to catch the server's SteamID the moment it's assigned. When the availability is equal to `SteamNetworkingAvailability.Current`, the SteamID is immediately available.
(My personal) use case is for relay server routing when a first-party matchmaking system is used.
> Add OnSteamNetAuthenticationStatus and SteamServer.SteamId

- Facepunch.Steamworks/SteamNetworkingSockets.cs
`SteamNetworkingSockets` exposes a way to create both normal socket server and relay socket server. The `CreateNormalSocket` supports both concrete class and interface approach when creating the server. However, for `CreateRelaySocket`, it does not have a way to use interface approach.
The interface approach is more convenient when building app using dependency injection framework so if `CreateNormalSocket` supports the interface approach, why not having `CreateRelaySocket` support it as well?
> Interface approach for CreateRelaySocket

- Facepunch.Steamworks.Test/ClanTest.cs
- Facepunch.Steamworks/SteamFriends.cs
- Facepunch.Steamworks/Structs/Clan.cs
Since none of the clan-related function were implemented (and I wanted to utilize the clan tags for a project), I've decided to implement some. 
All the clan functions reside in the Clan struct. A list of clans for the currently logged in user is also accessible via `SteamFriends.GetClans()`
Of course, not all clan functions are implemented yet, but the ones in here so far should be plenty enough for most people.
> Steam Clans support

- Facepunch.Steamworks/Structs/UgcItem.cs
- Facepunch.Steamworks/Structs/UgcQuery.cs
- Facepunch.Steamworks/Structs/UgcResultPage.cs
Just a minor change to add support for getting the metadata of UGC items.
The TODO was a great help :) Since most of it was already there, I'm not sure if I am missing something here, since it feels a bit weird that it was left as a TODO but it works fine in the initial testing I have done.
> Support return UGC metadata in query

- Facepunch.Steamworks/Structs/Lobby.cs
Without null terminator in a message of Lobby.SendChatString - later on when reading it - the Helpers.MemoryToString  won't stop and returns invalid characters at the end of received one.
At start tried Helpers.TakeMemoryZeroedOut() in OnLobbyChatMessageRecievedAPI instead and also worked fine:
```
public static unsafe IntPtr TakeMemoryZeroedOut()
{
lock ( MemoryPool )
{
var pool = TakeMemory();
Unsafe.InitBlockUnaligned( pool.ToPointer(), 0, MemoryBufferSize );
return pool;
}
}
```
> Lobby.SendChatString() and OnChatMessage fix

- Facepunch.Steamworks/Callbacks/CallResult.cs
The initial await on a call like CreateLobbyAsync will immediately call IsCompleted from that context. OnCompleted will be called later when the task actually starts running. If the SteamAPICallCompleted_t is posted in between those calls, we miss it since we didn't register our continuation yet so the task never finishes.
> Fix race condition with async callresults

- Facepunch.Steamworks/SteamUgc.cs
Methods for suspending and resuming workshop downloads were implemented, but were not opened to library users.
> SuspendDownloads added to public API

- Facepunch.Steamworks/Structs/UgcEditor.cs
The enum value was already there, I just needed hidden items in the workshop for replays. This allows you to create workshop items, that are hidden from users, but still queryable
> Add game managed UGC Items

- Facepunch.Steamworks/Structs/UgcEditor.cs
In my project this is required as I'm adding workshop id of created item to files of that item before updating it.
There are more use cases. For ex. currently when item creation succeeds but updating fails it's impossible to react properly as function only returns Result.Fail.
> UgcEditor.SubmitAsync, on item created callback

- Facepunch.Steamworks/SteamNetworking.cs
This PR exposes a version of `IsP2PPacketAvailable` that also provides the size of the packet.
The original Steam API includes a the message size in `IsP2PPacketAvailable`. The current implementation deliberately drops it, because the main entry point using it (`ReadP2PPacket`) uses an internal buffering system (`Helpers.TakeBuffer`) that shields any user from having to use it... except when you want to manage your buffers yourself.
I am not sure if there are any other steps needed to move this PR forward, but please do let me know if I'm missing something.
> Expose message size in IsP2PPacketAvailable

- README.md
Fixes a syntax error ( too many closing braces) in an code example on the README.
> Fixes typo in README Achievements code example

- Facepunch.Steamworks/Networking/Connection.cs
It's crucial for the HashSet usage at SocketManager.
> Override connection's GetHashCode()

- Facepunch.Steamworks/Structs/Lobby.cs
Also add a unsafe variant that would require zero copies to a managed array if a pointer is already available.
Might be easier if (ReadOnly)Span<byte> was used, but I'm not sure if that's currently supported on all platforms.
> Implement #523: Make Lobby.SendChatBytes public.

- Facepunch.Steamworks/Generated/Interfaces/ISteamAppList.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamApps.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamGameSearch.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamInventory.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamMatchmaking.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamNetworkingSockets.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamNetworkingUtils.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamParties.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamUGC.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamUser.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamUserStats.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamUtils.cs
- Facepunch.Steamworks/Generated/Interfaces/ISteamVideo.cs
- Facepunch.Steamworks/Networking/NetAddress.cs
- Facepunch.Steamworks/SteamFriends.cs
- Facepunch.Steamworks/SteamMatchmaking.cs
- Facepunch.Steamworks/Utility/Helpers.cs
- Generator/CodeWriter/Interface.cs
I ran into this issue by having a few too many tasks querying UGC item metadata at the same time, and luckily noticed that I was either getting empty strings or a null character at the start of my strings, indicating that there was a race condition here. Perhaps I'm simply misusing the library here by relying on parallelism on Ugc.Item too much, but I figured that if this library is going to make me use async then it's probably so I can use it this way.
> Fixed race condition caused by too many tasks using Helpers.TakeMemory simultaneously

- Facepunch.Steamworks/Networking/BroadcastBufferManager.cs
Discovered race condition when accidentally sending 200k packets per second. It will cause a hard crash from steamworks, specifically...
``Process terminated. A callback was made on a garbage collected delegate of type 'Facepunch.Steamworks.Win64!Steamworks.BufferManager+FreeFn::Invoke'.``
You need to keep a reference to the delegate otherwise it gets garbage collected. [I've essentially followed the example of a pre net5.0 unmanaged to managed callback found in this microsoft blogpost](https://devblogs.microsoft.com/dotnet/improvements-in-native-code-interop-in-net-5-0/#unmanagedcallersonly). It's the first codeblock after the linked anchor.
> Fix GC race condition in sending packets causing crash from steamworks

- Facepunch.Steamworks/Facepunch.Steamworks.Win32.csproj
- Facepunch.Steamworks/Facepunch.Steamworks.Win64.csproj
x64 build also copied 32-bit DLL.
Both packages didn't include their steam_api*dll when generated through VS.
> Fix NuGet package generation

- Facepunch.Steamworks/Structs/UgcEditor.cs
Adjusted uploading progress bar so it doesn't jump back after finishing uploading content.
(It jumps from 90% to 80% since progress was calculated using 0.2f + uploaded * 0.7f, I changed this to 0.2f + uploaded * 0.6f)
> Adjusted uploading progress bar so it doesn't jump back

- README.md
- Added `$` to two strings that contain interpolation strings but that are not actually interpolated.
- Removed ` `  (space) that seemed unnecessary.
> Fix strings in readme

- Facepunch.Steamworks/SteamRemoteStorage.cs
Without this check we might return an uninitialized buffer if FileRead fails.
> Check return value from FileRead

- Facepunch.Steamworks/SteamApps.cs
- Facepunch.Steamworks/SteamClient.cs
- Facepunch.Steamworks/SteamFriends.cs
- Facepunch.Steamworks/SteamInput.cs
- Facepunch.Steamworks/SteamInventory.cs
- Facepunch.Steamworks/SteamMatchmaking.cs
- Facepunch.Steamworks/SteamMatchmakingServers.cs
- Facepunch.Steamworks/SteamMusic.cs
- Facepunch.Steamworks/SteamNetworking.cs
- Facepunch.Steamworks/SteamNetworkingSockets.cs
- Facepunch.Steamworks/SteamNetworkingUtils.cs
- Facepunch.Steamworks/SteamParental.cs
- Facepunch.Steamworks/SteamParties.cs
- Facepunch.Steamworks/SteamRemotePlay.cs
- Facepunch.Steamworks/SteamRemoteStorage.cs
- Facepunch.Steamworks/SteamScreenshots.cs
- Facepunch.Steamworks/SteamServer.cs
- Facepunch.Steamworks/SteamServerStats.cs
- Facepunch.Steamworks/SteamUgc.cs
- Facepunch.Steamworks/SteamUser.cs
- Facepunch.Steamworks/SteamUserStats.cs
- Facepunch.Steamworks/SteamUtils.cs
- Facepunch.Steamworks/SteamVideo.cs
- Facepunch.Steamworks/Utility/SteamInterface.cs
Opening this up for potential discussion.
Handle Steam not running in a less crashy way, by bailing early during initialization. This should also allow devs to handle Steam not running better in their apps.
Does not handle closing Steam after initialization however.
> Handle Steam not running better

- Facepunch.Steamworks/SteamApps.cs
Super simple fix for OnNewLaunchParameters never getting called. Assuming InstallEvents was just forgotten in the SteamApps class. Guess not a lot of people are using that callback :P 
Fixes #553
> Fixes #553 OnNewLaunchParameters never getting called

- Facepunch.Steamworks/SteamClient.cs
Fixed typo inside SteamClient.cs. The typo is 'ureleased' and I changed it to 'unreleased'
From: SteamApi_Init returned false. Steam isn't running, couldn't find Steam, App ID is ureleased, Don't own App ID.
To: SteamApi_Init returned false. Steam isn't running, couldn't find Steam, App ID is unreleased, Don't own App ID.
> Fixed typo in SteamClient.cs

- Facepunch.Steamworks/SteamUser.cs
This PR fixes a bug where the session ticket array retrieved via `GetAuthSessionTicket` is truncated. Rather than `1024`, it seems like the max size retrieved for this session ticket array can be `2560` based on the C API docs in https://github.com/Facepunch/Facepunch.Steamworks/blob/aa87fe557fa0578b4361bf0f23848d64d0c94a79/Generator/steam_sdk/isteamuser.h#L432. 
This PR resolves that by increasing the size of the array used to match the C array max size, but I have not been able to test it as I haven't been able to build this solution on macOS. I've tested using the equivalent API in Steamworks.net which uses the right size and was able to verify that allows for a proper sign in using Unity Game Services (see issue https://github.com/Facepunch/Facepunch.Steamworks/issues/827).
Could …
> Fixed truncated session ticket array

- Facepunch.Steamworks/Structs/UgcEditor.cs
Fixed Tuple import error, changed some formatting
Copied from #796 : "Adds methods to expose [ISteamUGC.AddItemPreviewFile](https://partner.steamgames.com/doc/api/ISteamUGC#AddItemPreviewFile) and [ISteamUGC.RemoveItemPreview](https://partner.steamgames.com/doc/api/ISteamUGC#RemoveItemPreview). These let you upload multiple preview images for your workshop upload, without them you can only upload one."
Thank you @nrgill28 !
> Add support for additional workshop preview files
